### ISSUE TITLE
Strange problem detecting available Chromecasts

### ISSUE THREAD

**Issue by s-devaney** [videostream/cordova-chromecast#34]
Issue reproduced on the following devices using an unsigned debug APK:
LG G3 S (4.4.4)
Galaxy S5 (4.4.4)

Could not reproduce on:
Nexus 4 (4.4.4 & 5.0)
Nexus 6 (5.0)
Nexus 7 (4.4.4)
Galaxy Ace (4.4.4)
Galaxy S3 (4.2)

Steps to reproduce:
Open app, connect to a Chromecast (using standard requestSession)
End/close the app (holding down home button/using menu button and swiping to remove the app)
This will also close the receiver file as number of senders=0 using window.close()
Open the app again and a Chromecast won't be found
To fix this issue requires re-installing the app or clearing the apps cache

Is this an issue with this plugin or are we doing something wrong?

**Comment by MrPeproni** [comment]
@s-devaney Please check this issue if you can help me...

https://github.com/videostream/cordova-chromecast/issues/67

**Comment by aditya27dev** [comment]
@s-devaney can you please share your code or an example project please?

**Comment by s-devaney** [comment]
Issue was on my side. Closed.
